PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/samsung/grandpplteser/proprietary/system/lib,system/lib)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/samsung/grandpplteser/proprietary/system/lib64,system/lib64)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/samsung/grandpplteser/proprietary/system/bin,system/bin)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/samsung/grandpplteser/proprietary/system/etc,system/etc)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/samsung/grandpplteser/proprietary/system/usr,system/usr)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/samsung/grandpplteser/proprietary/system/vendor,system/vendor)